import {
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  avatar6,
  avatar7,
  avatar8,
} from "../../../image";

export const dataDokter = [
  {
    id: 1,
    image: avatar1,
    doctorName: "dr. Darlene Robertson",
    email: "alma.lawson@example.com",
    telephone: "08123189239",
    workTime: "200 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "364723648632647",
    gender: "Perempuan",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 2,
    image: avatar2,
    doctorName: "dr. Albert Flores",
    email: "willie.jennings@example.com",
    telephone: "08123189239",
    workTime: "1000 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "274763287647326",
    gender: "Laki-laki",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 3,
    image: avatar3,
    doctorName: "dr. Bessie Cooper",
    email: "tim.jennings@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "3479382798372499",
    gender: "Wanita",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 4,
    image: avatar4,
    doctorName: "dr. Marvin McKinney",
    email: "michael.mitc@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "394763274893274",
    gender: "Laki-laki",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 5,
    image: avatar5,
    doctorName: "dr. Ralph Edwards",
    email: "debra.holt@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "847587236497334",
    gender: "Laki-laki",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 6,
    image: avatar6,
    doctorName: "dr. Esther Howard",
    email: "abill.sanders@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "374589237489732",
    gender: "Laki-laki",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 7,
    image: avatar7,
    doctorName: "dr. Darrell Steward",
    email: "kenzi.lawson@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "754832768773298",
    gender: "Laki-laki",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
  {
    id: 8,
    image: avatar8,
    doctorName: "dr. Alika Angelina",
    email: "jessica.hanson@example.com",
    telephone: "08123189239",
    workTime: "525 Jam",
    action: "...",
    job: "Psikologi Klinis",
    nik: "384932840982394",
    gender: "Perempuan",
    birth: "31 Desember 2023",
    hometown: "Surabaya",
    university: "Universitas Indonesia",
    departement: "S1 - Psikologi",
    period: "2020-2024",
  },
];

// export const columnUser = [
//     {
//         field: 'nama',
//         header: 'Nama',
//     },
//     {
//         field: 'email',
//         header: 'Email',
//     },
//     {
//         field: 'telepon',
//         header: 'No. Telp',
//     },
//     {
//         field: 'status_akun',
//         header: 'Status Akun',
//     },
//     {
//         field: 'action',
//         header: 'Action',
//     },

// ]
